version: "3.9"
services:
    next:
        build: .
        container_name: next
        stdin_open: true
        tty: true
        command: bash
        volumes:
            - ./next:/next
